name: Webstudio API WS Deploy Development
on:
  push:
    branches:
      - development
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Caching
        id: react-cache-build
        uses: actions/cache@v2
        with:
          path: |
            public
            .cache
            node_modules
          key: ${{ runner.os }}-webstudio-api-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-webstudio-api
      - name: Install dependencies
        run: npm i; cd lambda; npm i
      - name: cdk deploy
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'deploy'
          cdk_stack: 'WebstudioApiStack'
          cdk_args: '--require-approval never'
          actions_comment: false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          ACM_ARN: ${{ secrets.ACM_ARN_DEV }}
          AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT_DEV }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          CHATGPT_API: ${{ secrets.CHATGPT_API }}
          ROOT_DOMAIN: dev.webstudio.so